import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Space, Alert } from 'antd'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ant Typescript Web site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Space direction="vertical" style={{ width: '100%' }}>
            <Alert message="Success Tips" type="success" showIcon />
            <Alert message="Informational Notes" type="info" showIcon />
            <Alert message="Warning" type="warning" showIcon closable />
            <Alert message="Error" type="error" showIcon />
            <Alert
                message="Success Tips"
                description="Detailed description and advice about successful copywriting."
                type="success"
                showIcon
            />
            <Alert
                message="Informational Notes"
                description="Additional description and information about copywriting."
                type="info"
                showIcon
            />
            <Alert
                message="Warning"
                description="This is a warning notice about copywriting."
                type="warning"
                showIcon
                closable
            />
            <Alert
                message="Error"
                description="This is an error message about copywriting."
                type="error"
                showIcon
            />
        </Space>
      </main>
    </div>
  )
}
