import Head from 'next/head'
import Navbar from '../components/navbar'
import style from '../styles/index.module.css'

export default function Home() {
  return (
    <div>
        <Head>
            <title>Ant Typescript Web site</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={style.App}>
            <Navbar />
            <h1>Hello CodeSandbox</h1>
            <h2>Start editing to see some magic happen!</h2>
        </div>
    </div>
  )
}
